# Header
menu:
  Home: /
  Blog: /blog

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Google Analytics Tracking ID
google_analytics: UA-93916522-1

# Miscellaneous
favicon: images/favicon
twitter:
google_plus:
fb_admins:
fb_app_id:

stylus:
  compress: false
